### ISSUE TITLE
Missing kindleunpack error on win7

### ISSUE THREAD

**Issue by Uwe-B** [Markismus/PocketBookDic#2]
Hi, I got a problem with the last version:
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Alle Rechte vorbehalten.

E:\Download\ebook\Pocketbook\Dic\__neu_am_allerbesten\PocketbookDic>perl pocketb
ookdic.pl
syntax error at pocketbookdic.pl line 25, near "my "
Global symbol "$KindleUnpackLibFolder" requires explicit package name (did you f
orget to declare "my $KindleUnpackLibFolder"?) at pocketbookdic.pl line 25.
BEGIN not safe after errors--compilation aborted at pocketbookdic.pl line 56.

E:\Download\ebook\Pocketbook\Dic\__neu_am_allerbesten\PocketbookDic>

Basedir and are KindleUnpackLibFolder defined properly:
my $BaseDir="E:/Download/ebook/Pocketbook/Dic/__neu_am_allerbesten/PocketbookDic"
my $KindleUnpackLibFolder="E:/Download/ebook/Pocketbook/Dic/__neu_am_allerbesten/PocketbookDic/_KindleUnpack-083/lib";
tried even:
my $KindleUnpackLibFolder="_KindleUnpack-083/lib";

Nothing works. Any ideas? Thanks for the script btw.

**Comment by Markismus** [comment]
Hey, sorry for the late response. 
You forgot to put a `;` at the end of the line `my $BaseDir="E:/Download/ebook/Pocketbook/Dic/__neu_am_allerbesten/PocketbookDic"`

**Comment by Uwe-B** [comment]
Thanks, that was quite stupid of me. It solved the "issue".
