### ISSUE TITLE
Conversion of special characters to html entities (e.g. ' to &apos;) causes failed search in Koreader

### ISSUE THREAD

**Issue by 0capitao** [Markismus/PocketBookDic#5]
I stumbled upon your script on the mobileread forum and first wanted to say thank you for sharing your work :-)

I tried to use the script to convert a Stardict dictionary with xdxf tags to a Stardict dictionary with html tags, so that it is displayed properly in Koreader (on Android and Pocketbook). On first glance it works fine, but it seems that the conversion of special characters to html entities (e.g. _'_ to _\&apos;_) in the .idx file causes the dictionary search in Koreader to fail for entries that contain one of those characters (e.g _'cause_). Koreader does not seem to interpret the entities as the corresponding symbols but as plain text. E.g. now I have to search for _\&apos;cause_ in the reconstructed dictionary to find the entry for _'cause_.

Is there a way to avoid/fix this?

Thanks a lot in advance!

**Comment by Markismus** [comment]
Yes. There are toggles. Eventually all control variables should be exported by their module and manually controlled by `DicToggles`. However,  I haven't fleshes them all out into their modules and `DicToggles`, so most still are in the module `DicGlobal`. 

As the amount of control variables grew, I packaged them into two toggles: `$Just4Koreader` and `$Just4Pocketbook`.
However, the sub `unEscapeHTMLString` actually does the work and the toggle `$unEscapeHTML` controls the use of it on the whole reconstructed dictionary. What is odd, though, is that is set to 0, for `$Just4Koreader=1` and `$Just4Pocketbook=0`.

If your problem remains, could you please upload your _unconverted_ dictionary and post a link.

**Comment by 0capitao** [comment]
Thanks for your reply. The dictionary that I am trying to convert can be found [here](https://sourceforge.net/projects/xdxf/files/dicts-stardict-form-xdxf/001/stardict-comn_dsl02_mwc-2.4.2.tar.bz2/download).

I tried to set `$unEscapeHTML = 1`. This leads to the desired result for the **.idx** file. Special characters are kept like they are in the original dictionary and are not converted to html entities (e.g. _'cause_ instead of _\&apos;cause_).

But it also transforms html entities that are present in the original **.dict** file to the actual characters. This results in Koreader not displaying these entries correctly because they are not correct html.

Example:
Entry for _'ll_ in original dictionary with example text between _\&lt;_ and _\&gt;_
```
<k>'ll</k>
<co><c><i>verb</i></c></co>
 <co><b>Date:</b> 1578</co>
 <dtrn> <kref>will</kref> </dtrn> <c c="dimgray">&lt;<ex>you<i>'ll</i> be late</ex>&gt;</c>
```

Entry for _'ll_ in converted dictionary with `$unEscapeHTML = 1`. _\&lt;_ is converted to _<_ and _\&gt;_ to _>_ resulting in incorrect html
```
<k>'ll</k>
<co><span><i>verb</i></span></co>
 <co><b>Date:</b> 1578</co>
 <dtrn> <kref>will</kref> </dtrn> <span style="color:#696969"><<ex>you<i>'ll</i> be late</ex>></span>
```

I think what would be necessary would be an option to not change anything regarding special characters and html entities. So you could keep the special characters in the .idx file (so they can be found via Koreader) and the html entities in the .dict file (so they do not mess up the html code for the entries).

**Comment by Markismus** [comment]
Absolutely, this is not wanted behaviour. Nice catch! I remember that I prevented this issue once and now it seems to have snuck back in. I'll try to look into it this week.

**Comment by Markismus** [comment]
Yes, indeed I had fixed it (partially) in sub `arCleanse` in module `DicPrepare`. However, I had a parallel piece of code in its own subroutine, that didn't check anything before substitution. It's fixed. Thanks for noticing the bug! Could you please pull the latest commit for testing?

Still have to look into it how and why the sub `arCleanse` converts anything.  This is ancient code, haven't looked at it for ages. Probably was supposed to fix non-HTML dictionaries into _proper HTML_. (Nice how that ended up!) The pocketbook binary `converter.exe` is rather finicky and just getting it to work was the starting goal of the script.
For now, it seems unnecessary to escape the key values. Just escaping the description should do it. However, I'll have to test first.

**Comment by Markismus** [comment]
Current result is:
```xml
<article>
<key>&apos;ll</key>

<definition type="x">
<![CDATA[<k>'ll</k>
<co><span><i>verb</i></span></co>
 <co><b>Date:</b> 1578</co>
 <dtrn> <kref>will</kref> </dtrn> <span style="color:#696969">&lt;<ex>you<i>'ll</i> be late</ex>&gt;</span>]]>
</definition>
</article>
```
