### ISSUE TITLE
mobi dict

### ISSUE THREAD

**Issue by bawow50** [Markismus/PocketBookDic#7]
Hi, 
I have a question, I want to make a kindle dictionary from the Van Dale NLD-NLD dictionary. I have found this same dictionary   also on your linked pcloud account. I am a total noob, could you describe which steps I need to take in order to go from your linked xdxf file to a mobi format that the kindle will recognize as a usable dictionary? On newer devices e.g. paperwhite 2, this dictionary is included by default, but I have an old device . Thanks

**Comment by Markismus** [comment]
Try [pyglossary](https://github.com/ilius/pyglossary): It has a mobi-format output
